-- Lederutfordringen seed content - 150 daily leadership/culture challenges
INSERT INTO public.kbfb_leader_challenges (sort_order, category, text)
SELECT * FROM (VALUES
  (0, 'Arbeidsmiljø', 'Spør en ansatt hvordan helgen var, og lytt uten å avbryte.'),
  (1, 'Hyggelig', 'Kjøp noe godt til pausen - uten grunn, bare fordi.'),
  (2, 'Ledelse', 'Gi konkret, spesifikk tilbakemelding til noen på noe de gjorde denne uken.'),
  (3, 'Arbeidsmiljø', 'Ha en kort, uformell prat med noen du sjelden snakker med til vanlig.'),
  (4, 'Hyggelig', 'Skriv en kort, konkret ros-lapp til en ansatt og legg den et sted de finner den.'),
  (5, 'Ledelse', 'Sett av 15 minutter til å tenke fremover, uten avbrytelser.'),
  (6, 'Arbeidsmiljø', 'Spør teamet: "Hva trenger dere mer av fra meg akkurat nå?"'),
  (7, 'Hyggelig', 'Ta med kaffe/te til noen som står midt i en travel dag.'),
  (8, 'Ledelse', 'Spør deg selv: "Hva har jeg utsatt lenge som jeg bør ta tak i nå?"'),
  (9, 'Arbeidsmiljø', 'Gjennomfør en kort "hvordan har vi det"-runde på et personalmøte.'),
  (10, 'Hyggelig', 'Send en melding til en ansatt og fortell noe spesifikt du satte pris på denne uken.'),
  (11, 'Ledelse', 'Deleger en oppgave du vanligvis gjør selv, til noen som kan vokse på det.'),
  (12, 'Arbeidsmiljø', 'Spør en ansatt om noe de er stolte av å ha fått til denne uken.'),
  (13, 'Hyggelig', 'Overrask med noe hjemmebakst en helt vanlig tirsdag.'),
  (14, 'Ledelse', 'Be om tilbakemelding på egen ledelse fra en du stoler på.'),
  (15, 'Arbeidsmiljø', 'Sjekk at alle i dagens vaktlag faktisk fikk pause.'),
  (16, 'Hyggelig', 'Spør en ansatt om noe hyggelig fra privatlivet, og husk å følge opp senere.'),
  (17, 'Ledelse', 'Skriv ned tre ting du er usikker på som leder, og be om innspill fra noen.'),
  (18, 'Arbeidsmiljø', 'Spør om det er noe i den fysiske arbeidsdagen (utstyr, klær, pauser) som kunne vært bedre.'),
  (19, 'Hyggelig', 'Gi noen fri litt tidligere en dag det er mulig, uten at de ba om det.'),
  (20, 'Ledelse', 'Ta en beslutning du har utsatt, i stedet for å vente på perfekt informasjon.'),
  (21, 'Arbeidsmiljø', 'Gi rom for at noen kan si "jeg er sliten i dag" uten at det blir et problem.'),
  (22, 'Hyggelig', 'Heng opp noe hyggelig (bilde, sitat, tegning fra et barn) et sted ansatte ser det.'),
  (23, 'Ledelse', 'Gjennomgå en rutine og spør: "Trenger vi egentlig dette lenger?"'),
  (24, 'Arbeidsmiljø', 'Spør en ansatt hva som gjør en god dag på jobb for dem.'),
  (25, 'Hyggelig', 'Ta initiativ til en liten quiz eller lek i en pause.'),
  (26, 'Ledelse', 'Sett et konkret, lite mål for uken og følg det opp fredag.'),
  (27, 'Arbeidsmiljø', 'Ta initiativ til en liten oppsummering på slutten av dagen: hva gikk bra?'),
  (28, 'Hyggelig', 'Gi en ansatt et kompliment for noe helt konkret de gjorde i dag, ansikt til ansikt.'),
  (29, 'Ledelse', 'Spør en ansatt om et forslag til forbedring, og gjennomfør det faktisk.'),
  (30, 'Arbeidsmiljø', 'Spør om noen føler seg oversett i planleggingen av noe.'),
  (31, 'Hyggelig', 'Send en oppmuntrende melding til noen som har en tung uke.'),
  (32, 'Ledelse', 'Reflekter over en vanskelig samtale du har utsatt - og book den.'),
  (33, 'Arbeidsmiljø', 'Inviter til en åpen runde: "Er det noe dere lurer på, men ikke har spurt om?"'),
  (34, 'Hyggelig', 'Sørg for blomster eller noe grønt et sted i personalrommet.'),
  (35, 'Ledelse', 'Les eller lær noe nytt om ledelse i 20 minutter, og skriv ned én ting du tar med deg.'),
  (36, 'Arbeidsmiljø', 'Sjekk at nye ansatte/vikarer faktisk føler seg inkludert, ikke bare introdusert.'),
  (37, 'Hyggelig', 'Skriv en kort takk-e-post til hele teamet for innsatsen en spesiell uke.'),
  (38, 'Ledelse', 'Spør deg selv om du gir nok ansvar til andre, eller om du holder for mye selv.'),
  (39, 'Arbeidsmiljø', 'Spør en ansatt om et konkret forslag til hvordan en rutine kan bli enklere.'),
  (40, 'Hyggelig', 'Ta et bilde av noe fint i hverdagen og del det med teamet.'),
  (41, 'Ledelse', 'Sett av tid til å planlegge en samtale du gruer deg til, i stedet for å improvisere.'),
  (42, 'Arbeidsmiljø', 'Ta en tur ut i avdelingen bare for å være til stede, ikke for å sjekke noe.'),
  (43, 'Hyggelig', 'Gi noen et lite gavekort eller en billig, hyggelig ting uten anledning.'),
  (44, 'Ledelse', 'Følg opp et løfte du har gitt, som du ikke har fulgt opp ennå.'),
  (45, 'Arbeidsmiljø', 'Spør: "Er det noe som stresser deg i hverdagen som vi kan gjøre noe med?"'),
  (46, 'Hyggelig', 'Spør om noen har bursdag snart, og planlegg noe lite og hyggelig.'),
  (47, 'Ledelse', 'Spør en avdelingsleder hva de trenger mer støtte til.'),
  (48, 'Arbeidsmiljø', 'Gi noen mulighet til å prøve en oppgave de ikke har gjort før.'),
  (49, 'Hyggelig', 'Lag en "gladlapp"-runde der ansatte skriver noe hyggelig om hverandre.'),
  (50, 'Ledelse', 'Gi tydelig, ærlig tilbakemelding på noe som ikke fungerer, med respekt.'),
  (51, 'Arbeidsmiljø', 'Spør om samarbeidet mellom avdelingene funker greit fra deres ståsted.'),
  (52, 'Hyggelig', 'Overrask med is eller frukt en varm dag.'),
  (53, 'Ledelse', 'Sett deg ett konkret mål for hvordan du vil utvikle deg som leder denne måneden.'),
  (54, 'Arbeidsmiljø', 'Sørg for at en vanskelig avgjørelse blir forklart, ikke bare meddelt.'),
  (55, 'Hyggelig', 'Fortell en kollega direkte: "Jeg er glad du jobber her."'),
  (56, 'Ledelse', 'Vurder om et møte kunne vært en kort melding i stedet.'),
  (57, 'Arbeidsmiljø', 'Spør en ansatt hva de skulle ønske ledelsen visste, men kanskje ikke vet.'),
  (58, 'Hyggelig', 'Ta initiativ til felles lunsj en dag det ellers ville vært hver for seg.'),
  (59, 'Ledelse', 'Ta en beslutning basert på hva som er best for barna, ikke det som er enklest for deg.'),
  (60, 'Arbeidsmiljø', 'La noen få si sin mening FØR du sier din egen i en diskusjon.'),
  (61, 'Hyggelig', 'Spill av litt hyggelig musikk mens dere rydder sammen etter en lang dag.'),
  (62, 'Ledelse', 'Spør deg selv: "Er jeg tilgjengelig nok for teamet mitt akkurat nå?"'),
  (63, 'Arbeidsmiljø', 'Spør om noen sitter med en bekymring om et barn de vil dele.'),
  (64, 'Hyggelig', 'Skriv en personlig takk til en vikar for god innsats, ikke bare en generell melding.'),
  (65, 'Ledelse', 'Gi et team eller en ansatt mer eierskap til en beslutning enn du pleier.'),
  (66, 'Arbeidsmiljø', 'Ta initiativ til å rydde opp i en uklar rutine som skaper irritasjon.'),
  (67, 'Hyggelig', 'Gi et lite "utmerkelse"-diplom for noe morsomt (f.eks. "ukens tur-helt").'),
  (68, 'Ledelse', 'Reflekter over en konflikt du har unngått - og ta et lite steg mot å løse den.'),
  (69, 'Arbeidsmiljø', 'Spør: "Har vi nok folk på vakt de dagene som faktisk er tyngst?"'),
  (70, 'Hyggelig', 'Ta med noe varmt å drikke til noen som har stått mye ute.'),
  (71, 'Ledelse', 'Sett av 10 minutter til å skrive ned hva som går bra i barnehagen akkurat nå.'),
  (72, 'Arbeidsmiljø', 'Gi anerkjennelse til noen for noe de gjør jevnlig, men aldri får skryt for.'),
  (73, 'Hyggelig', 'Spør en kollega om noe de gleder seg til, og vis at du husker å spørre igjen.'),
  (74, 'Ledelse', 'Spør en mentor, kollega eller nettverk om råd i en sak du strever med.'),
  (75, 'Arbeidsmiljø', 'Spør en ansatt om det er noe fysisk (løft, lyd, lys) som plager dem i arbeidshverdagen.'),
  (76, 'Hyggelig', 'Lag en enkel "komplimentboks" der man kan legge inn hyggelige lapper til hverandre.'),
  (77, 'Ledelse', 'Vurder om du kommuniserer nok "hvorfor" bak beslutninger, ikke bare "hva".'),
  (78, 'Arbeidsmiljø', 'Ta deg tid til å forklare "hvorfor" bak en beslutning, ikke bare "hva".'),
  (79, 'Hyggelig', 'Overrask med at du tar en kjedelig oppgave for noen, uten at de trenger å be.'),
  (80, 'Ledelse', 'Ta initiativ til en kort evaluering av noe dere nylig gjennomførte.'),
  (81, 'Arbeidsmiljø', 'Spør om det er konflikter eller spenninger som trenger et rom å bli tatt opp i.'),
  (82, 'Hyggelig', 'Send en melding om morgenen som ønsker en fin dag, spesielt til noen som har hatt det tøft.'),
  (83, 'Ledelse', 'Spør deg selv om noen i teamet trenger tydeligere forventninger fra deg.'),
  (84, 'Arbeidsmiljø', 'Sjekk at noen som nylig har vært syk får en myk overgang tilbake.'),
  (85, 'Hyggelig', 'Ta initiativ til å feire en liten seier (godkjent søknad, ny vikar på plass, etc).'),
  (86, 'Ledelse', 'Gi ros til en ansatt for initiativ, selv om utfallet ikke ble perfekt.'),
  (87, 'Arbeidsmiljø', 'Spør teamet om noe dere gjør er unødvendig tungvint og kan forenkles.'),
  (88, 'Hyggelig', 'Gi et konkret "takk for i dag" før alle går hjem.'),
  (89, 'Ledelse', 'Sett av tid til å tenke på hvem som kan vokse inn i mer ansvar fremover.'),
  (90, 'Arbeidsmiljø', 'Gi et ærlig svar på et vanskelig spørsmål, i stedet for å pynte på det.'),
  (91, 'Hyggelig', 'Sett av 10 minutter til bare å prate med teamet, ikke om jobb.'),
  (92, 'Ledelse', 'Vurder om en av dine egne vaner bremser teamet (for sen respons, for mye detalj-styring).'),
  (93, 'Arbeidsmiljø', 'Spør om noen føler at arbeidsmengden er urettferdig fordelt.'),
  (94, 'Hyggelig', 'Skriv en hyggelig kommentar i Kjøkkenboka til noen som fortjener det.'),
  (95, 'Ledelse', 'Spør deg selv: "Hva ville jeg gjort annerledes om jeg startet i dag?"'),
  (96, 'Arbeidsmiljø', 'Ta initiativ til en kort "vi feirer" i fellesskap for noe som gikk bra.'),
  (97, 'Hyggelig', 'Gi noen et valg de vanligvis ikke får (velge tur, velge oppgave) som en liten gest.'),
  (98, 'Ledelse', 'Gi en avdelingsleder mandat til å ta en avgjørelse du normalt ville tatt selv.'),
  (99, 'Arbeidsmiljø', 'Spør en ansatt hva som ville gjort dem tryggere i jobben sin.'),
  (100, 'Hyggelig', 'Fortell en ansatt om noe positivt en forelder eller et barn har sagt om dem.'),
  (101, 'Ledelse', 'Skriv ned én ting du er stolt av å ha fått til som leder denne måneden.'),
  (102, 'Arbeidsmiljø', 'Sørg for at stillhet i et møte blir en invitasjon, ikke et press.'),
  (103, 'Hyggelig', 'Ta med noe hjemmefra som kan gjøre pauserommet litt triveligere.'),
  (104, 'Ledelse', 'Ta en vanskelig telefon eller samtale du har utsatt.'),
  (105, 'Arbeidsmiljø', 'Spør om noen kjenner seg alene om noe de bør dele byrden av.'),
  (106, 'Hyggelig', 'Del noe morsomt eller rørende fra hverdagen på et personalmøte.'),
  (107, 'Ledelse', 'Spør om det er en beslutningsprosess som tar unødvendig lang tid, og forenkle den.'),
  (108, 'Arbeidsmiljø', 'Gi rom for uenighet uten at det oppleves som illojalitet.'),
  (109, 'Hyggelig', 'Gi en uventet klapp på skulderen og et "bra jobba" midt i en travel dag.'),
  (110, 'Ledelse', 'Sett av tid til å tenke på barnehagens retning de neste 1-2 årene.'),
  (111, 'Arbeidsmiljø', 'Spør om noen har gode ideer til hvordan dere kan bli bedre kjent på tvers av avdelinger.'),
  (112, 'Hyggelig', 'Skriv et kort, ekte "jeg er stolt av deg" til noen som har strukket seg.'),
  (113, 'Ledelse', 'Gi konstruktiv, direkte tilbakemelding fremfor å la noe irritere deg over tid.'),
  (114, 'Arbeidsmiljø', 'Ta en telefon eller melding til noen som har hatt en tøff periode.'),
  (115, 'Hyggelig', 'Ta initiativ til felles kake en fredag uten spesiell anledning.'),
  (116, 'Ledelse', 'Spør deg selv om du lytter mer enn du snakker i møter denne uken.'),
  (117, 'Arbeidsmiljø', 'Spør: "Hva er det siste dere lo av sammen på jobb?"'),
  (118, 'Hyggelig', 'Spør om noen trenger noe fra butikken når du likevel skal handle.'),
  (119, 'Ledelse', 'Ta initiativ til å sette et tydelig mål teamet kan strekke seg mot sammen.'),
  (120, 'Arbeidsmiljø', 'Sjekk at introduksjonen for en ny ansatt faktisk føles trygg, ikke bare effektiv.'),
  (121, 'Hyggelig', 'Gi et lite pusterom - overta et barn/en oppgave fem minutter så noen kan puste ut.'),
  (122, 'Ledelse', 'Vurder om noen trenger mer opplæring eller støtte for å lykkes i rollen sin.'),
  (123, 'Arbeidsmiljø', 'Spør om noen trenger avlastning en periode, uten at de trenger å be om det selv.'),
  (124, 'Hyggelig', 'Send en morsom, hyggelig gif eller melding i en felles chat.'),
  (125, 'Ledelse', 'Gi anerkjennelse til en avdelingsleder for jobben de gjør med å lede andre.'),
  (126, 'Arbeidsmiljø', 'Gi ansvar til noen som sjelden får det, og vis at du stoler på dem.'),
  (127, 'Hyggelig', 'Fortell teamet noe du har lært av dem denne måneden.'),
  (128, 'Ledelse', 'Sett av tid til å følge opp en beslutning: ble det som planlagt?'),
  (129, 'Arbeidsmiljø', 'Spør om det er noe i turnusen som sliter unødvendig på noen.'),
  (130, 'Hyggelig', 'Ta initiativ til en enkel "walk and talk" med en ansatt i stedet for møte inne.'),
  (131, 'Ledelse', 'Spør deg selv hvilken beslutning du tar av vane, ikke fordi den er riktig.'),
  (132, 'Arbeidsmiljø', 'Ta initiativ til å rydde vekk en kilde til frustrasjon i fellesarealene.'),
  (133, 'Hyggelig', 'Overrask med varme boller eller vafler en gråværsdag.'),
  (134, 'Ledelse', 'Ta initiativ til å rydde i egen kalender for å få mer tid med folkene dine.'),
  (135, 'Arbeidsmiljø', 'Spør en ansatt hva de synes fungerer bra med samarbeidet akkurat nå.'),
  (136, 'Hyggelig', 'Skriv en liten hilsen på tavlen/oppslagstavlen som starter dagen fint.'),
  (137, 'Ledelse', 'Gi tydelig beskjed om en forventning i stedet for å håpe folk skjønner det.'),
  (138, 'Arbeidsmiljø', 'Sørg for at tilbakemeldinger går begge veier, ikke bare fra deg og ned.'),
  (139, 'Hyggelig', 'Spør noen om de vil ha selskap på en tur, bare for det sosiale.'),
  (140, 'Ledelse', 'Vurder om du feirer fremgang nok, ikke bare fokuserer på det som mangler.'),
  (141, 'Arbeidsmiljø', 'Spør om noen har forslag til hvordan pauser kan bli bedre brukt.'),
  (142, 'Hyggelig', 'Gi ros for innsatsen, ikke bare resultatet, når noe har vært vanskelig.'),
  (143, 'Ledelse', 'Spør en ansatt hva slags leder de trenger at du er for dem akkurat nå.'),
  (144, 'Arbeidsmiljø', 'Ta deg tid til å høre ferdig, selv når du tror du vet hva som kommer.'),
  (145, 'Hyggelig', 'Ta et minutt til å le sammen med teamet om noe som gikk skeis.'),
  (146, 'Ledelse', 'Ta et lite steg mot en langsiktig endring du har tenkt på lenge.'),
  (147, 'Arbeidsmiljø', 'Spør teamet: "Hva er vi gode på som vi ikke snakker nok om?"'),
  (148, 'Hyggelig', 'Avslutt uken med en enkel "tusen takk for denne uken" til alle sammen.'),
  (149, 'Ledelse', 'Avslutt dagen med å spørre deg selv: "Hva gjorde jeg i dag som gjorde meg til en bedre leder?"')
) AS v(sort_order, category, text)
WHERE NOT EXISTS (SELECT 1 FROM public.kbfb_leader_challenges);
